Add Japanese language file
ivaniskandar/shouko pull request #38
Opened 2022-01-25 21:39 UTC by shacho36p

Hello.

I made Japanese translation file for XPERI+.
Therefore, I will send it to you .

I'm sorry I'm unused to GitHub.

2022-01-26 12:06 UTC, ivaniskandar requested changes
Hi! Thanks for the translation. I'll handle the rest but FYI you've missed these file to translate. You can add it by yourself or put it in the comment here.

2022-01-26 12:06 UTC, ivaniskandar commented on app/src/main/res/values-ja/plurals.xml
> +    <plurals name="approved_link_list_title">
This one

2022-01-26 15:05 UTC, ivaniskandar commented
New string to translate:
`<string name="digital_assistant_action_label">Digital Assistant</string>`

2022-01-27 15:27 UTC, shacho36p reviewed
I have translated the files that were not translated and updated the strings.xml.
Thank you for your cooperation.

2022-01-28 03:44 UTC, ivaniskandar approved these changes

2022-01-28 04:12 UTC, ivaniskandar commented
Thanks for your help!

2022-01-28 04:12 UTC, merged